### ISSUE TITLE
An outline with `gO` is broken

### ISSUE THREAD

**Issue by kjuq** [itchyny/vim-qfedit#12] opened 2024-02-19 14:06 UTC
## Description

In help documentations, `gO` shows an outline of the buffer (Only Neovim supports this). But current qfedit seems to break this function.
Though pressing `gO` creates a new quickfix buffer, it shows nothing.

## How to reproduce

```bash
cd /tmp
git clone https://github.com/itchyny/vim-qfedit
echo 'vim.opt.rtp:append("/tmp/vim-qfedit/")' > init.lua
nvim -u /tmp/init.lua
```

then

```vim
:help vim
```

finally type `gO`

## Current behavior

<img width="1920" alt="Screenshot 2024-02-19 at 22 45 25" src="https://github.com/itchyny/vim-qfedit/assets/44694396/9409b0bb-423b-46b9-b953-a9339ce5b011">

## Expected behavior

<img width="1920" alt="Screenshot 2024-02-19 at 22 47 56" src="https://github.com/itchyny/vim-qfedit/assets/44694396/ac133df3-1c7f-43be-bf18-75cb80a48f63">

## Version

```bash
nvim --version
```

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info
```

and

```
NVIM v0.10.0-dev-2398+gcc15ba212-Homebrew
Build type: Release
LuaJIT 2.1.1703358377
Run "nvim -V1 -v" for more info
```

**Comment by itchyny** [comment] 2024-02-20 07:22
This is caused by the qf ftplugin of NeoVim https://github.com/neovim/neovim/blob/8952a89db588db10a9dba16356f9bbd35ca5fabb/runtime/ftplugin/qf.vim#L30-L35. I submitted https://github.com/neovim/neovim/pull/27547, so let's wait for their response.

**Comment by itchyny** [comment] 2024-02-20 13:27
Since Neovim included the patch, closing this issue.

**Closed as completed by itchyny** 2024-02-20 13:27 UTC
